//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYUPTZControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pc-config.av.byu.edu/{hostname}/config")]
        public string ConfigurationURL {
            get {
                return ((string)(this["ConfigurationURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IutzKHz1LFrvUAiMtW65R+oGQ2CWfIsnDz/8YP0w4gZeonV0c9DjPCfuZCq1+1MImT/R5RaA63+HpaIpd" +
            "rJ12cno0GDxkPxvodGaZasaarIsVXKOTrlOR+BB02ReWkPO")]
        public string CamPreviewTokenPayloadEncrpyted {
            get {
                return ((string)(this["CamPreviewTokenPayloadEncrpyted"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{hostname}/login_name")]
        public string CamPreviewTokenURL {
            get {
                return ((string)(this["CamPreviewTokenURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{hostname}:81/live")]
        public string CamPreviewURL {
            get {
                return ((string)(this["CamPreviewURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://{hostname}/rmt_acs")]
        public string CamPreviewSubscribeURL {
            get {
                return ((string)(this["CamPreviewSubscribeURL"]));
            }
        }
    }
}
